apiVersion: v1
kind: Template
metadata:
  name: mplat-dsf-base-buildconfig-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      build: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: ${REGISTRY_URL}/${APPLICATION_NAME}:${OUTPUT_IMAGE_TAG}
      pushSecret:
        name: artifactory
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:latest
          namespace: openshift
      type: Source
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name for the application.
  value: ${APPLICATION_NAME}
  required: true
- name: REGISTRY_URL
  displayName: Url to Docker Registry for output Image
  description: Url to Docker Registry for output Image
  value: mobile-docker-1.repos.fismobile.com/test
  required: true
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: Output Image Tag
  value: latest
  required: true
