kind: Template
apiVersion: v1
metadata:
  name: build-deploy-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}-openjdk18
    name: openjdk18-openshift
  spec:
    tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      generation: 1
      importPolicy: {}
      name: latest
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    triggers: []
    source:
      type: Binary
      binary: {}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: openjdk18-openshift:latest
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:${OUTPUT_IMAGE_TAG}"
    resources: {}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  displayName: Application name
  required: true
- name: OUTPUT_IMAGE_TAG
  description: The tag of the image built
  displayName: The tag of the image built
  required: true
  value: "latest"
