kind: Template
apiVersion: v1
metadata:
  name: deploy-service-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: The application port.
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
   ports:
   - name: 8080-tcp
     protocol: TCP
     port: 8080
     targetPort: 8080
   selector:
     deploymentconfig: "${APPLICATION_NAME}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
    replicas: 1
    selector:
      deploymentconfig: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          deploymentconfig: "${APPLICATION_NAME}"
          app: "${APPLICATION_NAME}"
      spec:
        containers:
        - env:
          - name: SERVER_PORT
            value: "8080"
          - name: APP_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          name: "${APPLICATION_NAME}"
          image: "${APPLICATION_NAME}"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
          ports:
          - containerPort: 8080
            protocol: TCP
            name: tcp-8080
          - containerPort: 8778
            protocol: TCP
            name: jolokia
          resources: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:${IMAGE_TAG}
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  displayName: Application name
  required: true
- name: IMAGE_NAME
  description: The name of the image.
  displayName: Image name
  required: true
- name: IMAGE_TAG
  description: Image tag to deploy
  displayName: Image tag to deploy
  required: true
