apiVersion: v1
kind: Template
metadata:
  name: image-inspector-pod-template
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: privileged
    creationTimestamp: null
    labels:
      app: image-inspector
    name: ${POD_NAME}
  spec:
    containers:
    - name: image-inspector
      image: registry.access.redhat.com/openshift3/image-inspector:latest
      command:
      - /usr/bin/image-inspector
      - --image=${IMAGE_URL}
      - --path=/tmp/image-content
      - --serve=0.0.0.0:8080
      - --chroot
      - --scan-type=openscap
      - --scan-results-dir=/tmp/image-content
      - --openscap-html-report
      - --dockercfg=/tmp/registry/.dockercfg
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 20
        periodSeconds: 15
        successThreshold: 1
        tcpSocket:
          port: 8080
        timeoutSeconds: 5
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-socket
      - mountPath: /tmp/registry
        name: docker-registry
    restartPolicy: Always
    securityContext: {}
    serviceAccount: image-inspector
    serviceAccountName: image-inspector
    volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: docker-registry
      secret:
        secretName: ${DOCKER_CONFIG_SECRET}
parameters:
- name: POD_NAME
  displayName: Pod Name
  description: The name assigened to pod running the OpenSCAP scan.
  required: true
- name: IMAGE_URL
  displayName: Image URL to scan with OpenSCAP
  description: The image to perform OpenSCAP scan over.
  value: registry.access.redhat.com/rhel7:latest
  required: true
- name: DOCKER_CONFIG_SECRET
  displayName: Docker Config Secret to pull image
  description: The docker config secret in the project used to authenticate image pull.
  required: true
