kind: Template
apiVersion: v1
metadata:
  name: route-template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
  wildcardPolicy: None
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  displayName: Application name
  required: true
